# Generated by Django 6.0.3 on 2026-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0003_student_dob_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
