# Generated by Django 6.0.3 on 2026-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(null=True),
        ),
    ]
