# Generated by Django 6.0.3 on 2026-04-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0009_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.student')),
            ],
        ),
    ]
