# Generated by Django 6.0.3 on 2026-04-25 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0015_studentexam_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModuleGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.student')),
            ],
        ),
    ]
