# Generated by Django 6.0.3 on 2026-05-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0020_accreditation_datarequest_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
