# Generated by Django 6.0.3 on 2026-04-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0004_student_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
