# Generated by Django 6.0.3 on 2026-04-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0005_course_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('courses', models.TextField(help_text='Separate courses with commas')),
            ],
        ),
    ]
