# Generated by Django 6.0.3 on 2026-04-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0011_exam_essayquestion_mcqquestion_studentexam_mcqanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic_Data_Identity_System.module'),
        ),
    ]
