# Generated by Django 6.0.3 on 2026-04-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0013_studentexamassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
