# Generated by Django 6.0.3 on 2026-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0014_studentexamassignment_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
