# Generated by Django 6.0.3 on 2026-05-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic_Data_Identity_System', '0021_staff_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phone',
            new_name='contact',
        ),
    ]
